version: "3.9"

services:
  msa-post-express:
    build:
      context: .
      dockerfile: Dockerfile.develop
    command: "npm run start:dev"
    ports: 
      - 3000:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    container_name: msa-post-express-dev

volumes:
  node_modules:
