name: CI
on:
  push:
    paths-ignore:
      - "deploy/**"
jobs:
  test:
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli:4.6
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run sonar
        if: success()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: npm run sonar

  docker:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    container: docker:latest
    services:
      dind:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2

      - name: Push image to ghcr
        run: >
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u hexdump95 --password-stdin
          docker build . -t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/} -t ghcr.io/$GITHUB_REPOSITORY:latest
          docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF##*/}
          docker push ghcr.io/$GITHUB_REPOSITORY:latest
